categorical_columns:
  - platform
  - country
  - campaign_type
  - campaign_id
  - model
  - manufacturer
  - mobile_classification

target_column: d120_rev

target_map:
  "No Revenue": 0
  "Low Revenue": 1
  "Top 50%": 2
  "Top 20%": 3
  "Top 5%": 4
  "Top 1%": 5

lgbm_classifier_params:
  n_estimators: 1000
  objective: "multiclass"
  num_class: 6
  metric: "multi_logloss"
  random_state: 42

lgbm_regressor_params:
  n_estimators: 1000
  random_state: 42

raw_training_data_path: data/raw/train_samples.parquet

processed_data_path: data/processed/