categorical_columns:
  - platform
  - country
  - campaign_type
  - campaign_id
  - model
  - manufacturer
  - mobile_classification

target_column: d120_rev

target_map:
  "Low Revenue": 0
  "Top 50%": 1
  "Top 20%": 2
  "Top 5%": 3
  "Top 1%": 4

lgbm_classifier_params:
  n_estimators: 1000
  objective: "multiclass"
  num_class: 5
  metric: "multi_logloss"
  random_state: 42

lgbm_regressor_params:
  n_estimators: 1000
  random_state: 42

raw_training_data_path: data/raw/train_samples.parquet

processed_data_path: data/processed/