categorical_columns:
  - country
  - platform
  - acquisition_channel
  - device_type
  - os_version
  - app_version
  - language

target_column: 120d_rev

cohorts: 
- Top 1%
- Top 5%
- Top 20%
- Top 50%
- Low Revenue

lgbm_classifier_params:
  n_estimators: 1000
  objective: "multiclass"
  num_class: 6
  metric: "multi_logloss"
  random_state: 42
  enable_categorical: true

lgbm_regressor_params:
  n_estimators: 1000
  random_state: 42
  enable_categorical: true

raw_data_path: data/raw/training_data.parquet
training_data_path: data/processed/training_data.parquet